### ISSUE TITLE
Add refresh button?

### ISSUE THREAD

**Issue by Idyllwilde** [TheTeaCat/albums-by-year#20]
First of all: great job on this! Been wanting this functionality in Spotify for quite some time.
Just one small request: would it be possible to add a refresh button in the page somewhere?
(1 click instead of 2 ^^)

**Comment by TheTeaCat** [comment]
Thank you!

I was intending to add a "refresh" button as part of implementing some client caching of user data (so you don't have to query the spotify API for your saved albums every time you load up the app). That's a bit of a non-trivial change & I just haven't gotten round to it given not many people use this thing.

I'll take a look at it over the next month or so when I can. In the meantime if anyone wants to tackle this themselves that'd be cool so I'll tag this as "help wanted".

**Comment by TheTeaCat** [comment]
All done! If you have it installed as an app and it doesn't update automatically then you might have to uninstall and then reinstall it to get the new version. There should now be a little "Logout" and "Refresh" button in the footer. :)

**Comment by Idyllwilde** [comment]
Thanks so much! I'm using it on a daily basis right now and I really love it.
I'm however completely new at this and don't really understand how to install this as an app. Do you have any links with documentation/tutorials on how to do this?

**Comment by TheTeaCat** [comment]
Awesome!

How you can install it will differ over devices, it's a Progressive Web App (PWA) so when you open it in a browser you should get some kind of prompt to install it. I'll need to know what device and browser you're using to be able to offer more help, or you should be able to find some documentation for it by searching something along the lines of "how to install PWA on iOS safari".

I should probably add some kind of install button to make it easier/clearer but PWAs are still gaining support so it's only a matter of time before this is solved some other way and if I recall from other projects, making your own install button can be a bit janky. I'll look into it though.

**Comment by TheTeaCat** [comment]
Working on issue #21 (Add a custom install button) to make the install process more obvious as if you dismiss the install notification some browsers give you then you'll never get it again and it can become a bit hidden away. For example, in Chrome on android it'll disappear to here:

![138408123_3578454155603893_6820164012013403868_n](https://user-images.githubusercontent.com/20339741/104381212-066e2f00-5524-11eb-95ee-7bd4323c6d08.png)
